server:
  port: 8080
  servlet:
    context-path: /crud

spring:
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://192.168.101.153:3306/nios?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update





