server:
  port: 8070
  servlet:
    context-path: /nios

spring:
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/nios?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.dto

#LOG4J
logging:
  config: src\main\resources\log4j.properties

#OSS配置
oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  keyid: LTAIppa2MDOi5MRS
  keysecret: 
  bucketname: nios
  filehost: excel-backup



